services:
  wiki-bot:
    image: ghcr.io/alexbernardi360/wiki-bot:latest
    # build: . # Uncomment if you want to build locally
    container_name: wiki-bot
    restart: always
    env_file:
      - .env
    volumes:
      - sqlite_data:/app/data
      - ./logs:/app/logs
    ports:
      - '3000:3000'

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.44
    command: --interval 300 --cleanup
    restart: always

volumes:
  sqlite_data:
